// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResourcesApi.Models;

#nullable disable

namespace ResourcesApi.Migrations
{
    [DbContext(typeof(ResourceDbContext))]
    [Migration("20220209224957_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ResourcesApi.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EligibilityCriteria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InternshipPeriod")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Stipend")
                        .HasColumnType("bit");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Google Summer of Code program is a program started by Google and has completed 16 years. It is a program that aims to promote open-source software development among university students. There are a few organizations and these organizations have mentors.",
                            Description = "You can work with famous organizations like, Debian, Fedora, GCC, FreeBSD, Git (Not GitHub), Gnome, OpenSUSE Arduino, and other more top names in Open Source community.",
                            EligibilityCriteria = "none",
                            InternshipPeriod = 3,
                            Name = "Google Summer of Code",
                            Stipend = true,
                            Url = "https://summerofcode.withgoogle.com/"
                        },
                        new
                        {
                            Id = 2,
                            Body = "If you want to intern at the Free Software Foundation and you know web development, systems, networking, software licensing you can consider the FSF internship program. It has pretty good projects over there and here you get to work with the organizations that sponsor the GNU Project.",
                            Description = "The oldest, mother of all organizations which started the free software movement. The Internship program runs thrice a year.",
                            EligibilityCriteria = "none",
                            InternshipPeriod = 3,
                            Name = "Free Software Foundation (FSF)",
                            Stipend = false,
                            Url = "https://www.fsf.org/volunteer/internships"
                        },
                        new
                        {
                            Id = 3,
                            Body = "X.Org Endless Vacation of Code (EVoC) is a Google Summer of Code (GSoC)-like project initiated in 2008 funded by the X.Org Foundation. It allows students to participate to X. Org-related projects during their vacation, at any time of the year.",
                            Description = "Project which develops, maintains, supports the free software stack for accelerated graphics for all graphics hardware.",
                            EligibilityCriteria = "none",
                            InternshipPeriod = 4,
                            Name = "X.Org Endless Vacation of Code",
                            Stipend = true,
                            Url = "https://www.x.org/wiki/XorgEVoC/"
                        },
                        new
                        {
                            Id = 4,
                            Body = "Redox is a general-purpose operating system written in pure Rust. The Redox OS Summer of Code is the primary use of donations to the Redox OS project. Here, the students who have already demonstrated a desire and ability to contribute to Redox OS get selected.",
                            Description = "Project to entice/enhance women participation in Rust, Clojure, JavaScript, PHP, Python, Ruby on Rails, Rails web framework etc.",
                            EligibilityCriteria = "For Girls only",
                            InternshipPeriod = 3,
                            Name = "Redox OS Summer of Code (RGSOC)",
                            Stipend = true,
                            Url = "https://railsgirlssummerofcode.org/blog/2017-07-12-namaste-rgsoc-2017"
                        },
                        new
                        {
                            Id = 5,
                            Body = "The Data Observation Network for Earth (DataONE) is a virtual organization dedicated to providing open, persistent, robust, and secure access to biodiversity and environmental data, supported by the U.S. National Science Foundation.",
                            Description = "A project to collect, understand earth observational data using a variety of sensors, testing and making cohesive sense out of the data collected.",
                            EligibilityCriteria = "none",
                            InternshipPeriod = 4,
                            Name = "Data Observation Network for Earth (DataONE)",
                            Stipend = true,
                            Url = "https://old.dataone.org/internships"
                        },
                        new
                        {
                            Id = 6,
                            Body = "Open Daylight Project‘s mission is to facilitate a community-led, industry-supported open source framework, including code and architecture, to accelerate and advance a common, robust Software-Defined Networking platform.",
                            Description = "FOSS Project which works to use and promote software-defined networking and network functions visualization.",
                            EligibilityCriteria = "none",
                            InternshipPeriod = 3,
                            Name = "OpenDaylight",
                            Stipend = true,
                            Url = "http://archive15.opendaylight.org/community/summer-intern-program"
                        },
                        new
                        {
                            Id = 7,
                            Body = " Open Mainframe Project Mentorship Program is the open-source program that is hosted by the Linux Foundation and aims to introduce everyone to the mainframe community and development environment on Linux.",
                            Description = "Open Mainframe Project also has its own open-source program and the mentees will be able to expand their knowledge on the mainframe technology. You’ll also help in contributing to open source projects which will make it easier for infrastructure applications to run on the mainframe.",
                            EligibilityCriteria = "none",
                            InternshipPeriod = 3,
                            Name = "Open Mainframe Project Mentorship Program",
                            Stipend = false,
                            Url = "https://www.openmainframeproject.org/projects/mentorship-program"
                        },
                        new
                        {
                            Id = 8,
                            Body = "Aims to help beginners get started with Open Source Development while encouraging diversity. Throughout the program, participants contribute to different projects under guidance of experienced mentors.",
                            Description = "Their mission is to impinge on every individual who has the zeal to learn more. Around the year we conduct several educational programs and offer internship opportunities to the youngsters so that they become industry-ready.",
                            EligibilityCriteria = "none",
                            InternshipPeriod = 3,
                            Name = "GirlsScript Summer of Code",
                            Stipend = true,
                            Url = "https://gssoc.girlscript.tech/"
                        },
                        new
                        {
                            Id = 9,
                            Body = "The Outreachy internship projects focus on programming, documentation, project marketing, etc. During the application process, you need to show some genuine eagerness that why you want to be an Outreachy intern and in turn, what you’re going to accomplish, and then how you plan to promote diversity and all sorts of things.",
                            Description = "Outreachy started in 2006, wrapped up, and started up again in 2010. I did share an interview with Maria Glukova which shared her experience. Twice a year it runs and has in excess of 30+ interns per year from 20+ projects including Debian, Redhat, OpenStack, and many others.",
                            EligibilityCriteria = "Women, trans and cisgendered women",
                            InternshipPeriod = 3,
                            Name = "Outreachy",
                            Stipend = true,
                            Url = "https://www.gnome.org/outreachy/"
                        },
                        new
                        {
                            Id = 10,
                            Body = "Google Season of Docs is a program by Google where technical writers and open source organizations come together and work on open source projects. They aim to raise awareness of open source, of docs, and of technical writing.",
                            Description = "Technical writers can spend three months working closely with an open-source community. Bring their technical writing expertise to the project’s documentation. Google uses Payoneer to pay a stipend to technical writers who have successfully completed their Season of Docs projects.",
                            EligibilityCriteria = "Women, trans and cisgendered women",
                            InternshipPeriod = 3,
                            Name = "Google Season of Docs",
                            Stipend = false,
                            Url = "https://developers.google.com/season-of-docs"
                        },
                        new
                        {
                            Id = 11,
                            Body = "The Season of KDE, hosted by the KDE community, is an outreach program for all individuals across the world. KDE is an international free software community that develops free and open-source software and you can contribute to KDE through the Season of KDE program. ",
                            Description = "Khan Academy is looking for talented software developers to create a free virtual classroom for the world. You can work on developing web solutions, data analysis developing classroom content, etc.",
                            EligibilityCriteria = "none",
                            Name = "Season of KDE",
                            Stipend = true,
                            Url = "https://season.kde.org/"
                        },
                        new
                        {
                            Id = 12,
                            Body = "A month-long celebration of open source software run by DigitalOcean. Here, you need to submit four or more quality pull requests. The main idea over here is that there’s no such thing as a selection criterion in this particular program. ",
                            Description = "You can contribute to participating projects on GitHub and even if you’re not able to make a large major contribution what you can get out of it is how to use Git and Github.",
                            EligibilityCriteria = "none",
                            InternshipPeriod = 1,
                            Name = "Digital Ocean Hacktoberfest",
                            Stipend = true,
                            Url = "https://hacktoberfest.digitalocean.com/"
                        });
                });

            modelBuilder.Entity("ResourcesApi.Models.ResourceApplicationPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("ApplicationPeriods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Month = "March",
                            ResourceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Month = "April",
                            ResourceId = 1
                        },
                        new
                        {
                            Id = 3,
                            Month = "April",
                            ResourceId = 2
                        },
                        new
                        {
                            Id = 4,
                            Month = "May",
                            ResourceId = 2
                        },
                        new
                        {
                            Id = 5,
                            Month = "January",
                            ResourceId = 3
                        },
                        new
                        {
                            Id = 6,
                            Month = "February",
                            ResourceId = 3
                        },
                        new
                        {
                            Id = 7,
                            Month = "March",
                            ResourceId = 3
                        },
                        new
                        {
                            Id = 8,
                            Month = "April",
                            ResourceId = 3
                        },
                        new
                        {
                            Id = 9,
                            Month = "May",
                            ResourceId = 3
                        },
                        new
                        {
                            Id = 10,
                            Month = "June",
                            ResourceId = 3
                        },
                        new
                        {
                            Id = 11,
                            Month = "July",
                            ResourceId = 3
                        },
                        new
                        {
                            Id = 12,
                            Month = "August",
                            ResourceId = 3
                        },
                        new
                        {
                            Id = 13,
                            Month = "September",
                            ResourceId = 3
                        },
                        new
                        {
                            Id = 14,
                            Month = "October",
                            ResourceId = 3
                        },
                        new
                        {
                            Id = 15,
                            Month = "November",
                            ResourceId = 3
                        },
                        new
                        {
                            Id = 16,
                            Month = "December",
                            ResourceId = 3
                        },
                        new
                        {
                            Id = 17,
                            Month = "February",
                            ResourceId = 4
                        },
                        new
                        {
                            Id = 18,
                            Month = "March",
                            ResourceId = 4
                        },
                        new
                        {
                            Id = 19,
                            Month = "April",
                            ResourceId = 4
                        },
                        new
                        {
                            Id = 20,
                            Month = "February",
                            ResourceId = 5
                        },
                        new
                        {
                            Id = 21,
                            Month = "March",
                            ResourceId = 5
                        },
                        new
                        {
                            Id = 22,
                            Month = "January",
                            ResourceId = 6
                        },
                        new
                        {
                            Id = 23,
                            Month = "February",
                            ResourceId = 6
                        },
                        new
                        {
                            Id = 24,
                            Month = "March",
                            ResourceId = 6
                        },
                        new
                        {
                            Id = 25,
                            Month = "February",
                            ResourceId = 7
                        },
                        new
                        {
                            Id = 26,
                            Month = "March",
                            ResourceId = 7
                        },
                        new
                        {
                            Id = 27,
                            Month = "April",
                            ResourceId = 7
                        },
                        new
                        {
                            Id = 28,
                            Month = "May",
                            ResourceId = 7
                        },
                        new
                        {
                            Id = 29,
                            Month = "June",
                            ResourceId = 7
                        },
                        new
                        {
                            Id = 30,
                            Month = "July",
                            ResourceId = 7
                        },
                        new
                        {
                            Id = 31,
                            Month = "August",
                            ResourceId = 7
                        },
                        new
                        {
                            Id = 32,
                            Month = "September",
                            ResourceId = 7
                        },
                        new
                        {
                            Id = 33,
                            Month = "January",
                            ResourceId = 8
                        },
                        new
                        {
                            Id = 34,
                            Month = "February",
                            ResourceId = 8
                        },
                        new
                        {
                            Id = 35,
                            Month = "February",
                            ResourceId = 9
                        },
                        new
                        {
                            Id = 36,
                            Month = "March",
                            ResourceId = 9
                        },
                        new
                        {
                            Id = 37,
                            Month = "April",
                            ResourceId = 9
                        },
                        new
                        {
                            Id = 38,
                            Month = "June",
                            ResourceId = 10
                        },
                        new
                        {
                            Id = 39,
                            Month = "July",
                            ResourceId = 10
                        },
                        new
                        {
                            Id = 40,
                            Month = "October",
                            ResourceId = 12
                        });
                });

            modelBuilder.Entity("ResourcesApi.Models.ResourceLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Remote",
                            ResourceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Remote",
                            ResourceId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Boston, US",
                            ResourceId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Remote",
                            ResourceId = 3
                        },
                        new
                        {
                            Id = 5,
                            Name = "Remote",
                            ResourceId = 4
                        },
                        new
                        {
                            Id = 6,
                            Name = "United States",
                            ResourceId = 5
                        },
                        new
                        {
                            Id = 7,
                            Name = "Remote",
                            ResourceId = 6
                        },
                        new
                        {
                            Id = 8,
                            Name = "Remote",
                            ResourceId = 7
                        },
                        new
                        {
                            Id = 9,
                            Name = "Remote",
                            ResourceId = 8
                        },
                        new
                        {
                            Id = 10,
                            Name = "Remote",
                            ResourceId = 9
                        },
                        new
                        {
                            Id = 11,
                            Name = "Remote",
                            ResourceId = 10
                        },
                        new
                        {
                            Id = 12,
                            Name = "Remote",
                            ResourceId = 11
                        },
                        new
                        {
                            Id = 13,
                            Name = "Remote",
                            ResourceId = 12
                        });
                });

            modelBuilder.Entity("ResourcesApi.Models.ResourceApplicationPeriod", b =>
                {
                    b.HasOne("ResourcesApi.Models.Resource", "Resource")
                        .WithMany("ApplicationPeriods")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("ResourcesApi.Models.ResourceLocation", b =>
                {
                    b.HasOne("ResourcesApi.Models.Resource", "Resource")
                        .WithMany("Locations")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("ResourcesApi.Models.Resource", b =>
                {
                    b.Navigation("ApplicationPeriods");

                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
